INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'GT2', 'Ariana', 'Cité Ettadhamen', 'Tadhamen');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'GT2', 'Ariana', 'El Mnihla', 'Tadhamen');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'GT1', 'Ariana', 'Kalaât El Andalous', 'Sidi Thabet');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'GT1', 'Ariana', 'L''Ariana Ville', 'Ariana-Borj Louzir');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'GT1', 'Ariana', 'Raoued', 'Raoued');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'GT1', 'Ariana', 'Sidi Thabet', 'Sidi Thabet');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'GT1', 'Ariana', 'Soukra', 'Ariana-Borj Louzir');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'GT2', 'Ben Arous', 'Ben Arous', 'Ben Arous');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'GT2', 'Ben Arous', 'Bou Mhel El Bassatine', 'Hammam Lif');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'GT2', 'Ben Arous', 'El Mourouj', 'Kabaria');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'GT2', 'Ben Arous', 'Ezzahra', 'Hammam Lif');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'GT2', 'Ben Arous', 'Fouchana', 'Mhamdia/Fouchana');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'GT2', 'Ben Arous', 'Hammam Chôtt', 'Hammam Lif');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'GT2', 'Ben Arous', 'Hammam Lif', 'Hammam Lif');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'GT2', 'Ben Arous', 'La Nouvelle Medina', 'Ben Arous');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'GT2', 'Ben Arous', 'Megrine', 'Ben Arous');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'GT2', 'Ben Arous', 'Mohamedia', 'Mhamdia/Fouchana');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'GT2', 'Ben Arous', 'Mornag', 'Morneg');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'GT2', 'Ben Arous', 'Radès', 'Hammam Lif');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Bizerte', 'Bizerte', 'Bizerte Nord', 'Bizerte');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Bizerte', 'Bizerte', 'Bizerte Sud', 'Bizerte Sud');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Bizerte', 'Bizerte', 'Djoumine', 'Sejnene');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Bizerte', 'Bizerte', 'El Alia', 'El Alia');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Bizerte', 'Bizerte', 'Ghar El Meleh', 'Ras Jebal');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Bizerte', 'Bizerte', 'Ghezala', 'Mateur');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Bizerte', 'Bizerte', 'Joumine', 'Mateur');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Bizerte', 'Bizerte', 'Mateur', 'Mateur');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Bizerte', 'Bizerte', 'Menzel Bourguiba', 'Menzel Bourguiba');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Bizerte', 'Bizerte', 'Menzel Djemil', 'Bizerte');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Bizerte', 'Bizerte', 'Ras Djebel', 'Ras Jebal');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Bizerte', 'Bizerte', 'Sedjnane', 'Sejnene');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Bizerte', 'Bizerte', 'Tinja', 'Menzel Bourguiba');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Bizerte', 'Bizerte', 'Utique', 'Mateur');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Bizerte', 'Bizerte', 'Zarzouna', 'Bizerte');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Nord Ouest 1', 'Béja', 'Amdoun', 'Amdoun');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Nord Ouest 1', 'Béja', 'Béja Nord', 'Béja');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Nord Ouest 1', 'Béja', 'Béja Sud', 'Béja');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Nord Ouest 1', 'Béja', 'Goubellat', 'Mjez El Bab');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Nord Ouest 1', 'Béja', 'Medjez El Bab', 'Mjez El Bab');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Nord Ouest 1', 'Béja', 'Nefza', 'Nefza');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Nord Ouest 2', 'Béja', 'Teboursouk', 'El-Krib');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Nord Ouest 1', 'Béja', 'Testour', 'Testour');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Nord Ouest 1', 'Béja', 'Tibar', 'Boussalem');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Sud Est', 'Gabès', 'El Hamma', 'El Hamma');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Sud Est', 'Gabès', 'El Metouia', 'Metouia');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Sud Est', 'Gabès', 'Gabes Medina', 'Gabès');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Sud Est', 'Gabès', 'Gabes Ouest', 'Gabès');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Sud Est', 'Gabès', 'Gabes Sud', 'Gabès');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Sud Est', 'Gabès', 'Ghanouch', 'Gabès');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Sud Est', 'Gabès', 'Mareth', 'Mareth');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Sud Est', 'Gabès', 'Matmata', 'Gabès Sud');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Sud Est', 'Gabès', 'Menzel El Habib', 'Metouia');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Sud Est', 'Gabès', 'Nouvelle Matmata', 'Gabès Sud');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Sud Ouest', 'Gafsa', 'Belkhir', 'El Ksar');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Sud Ouest', 'Gafsa', 'EL Guetar', 'El Ksar');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Sud Ouest', 'Gafsa', 'El Ksar', 'El Ksar');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Sud Ouest', 'Gafsa', 'Gafsa Nord', 'El Ksar');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Sud Ouest', 'Gafsa', 'Gafsa Sud', 'Gafsa');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Sud Ouest', 'Gafsa', 'Mdhila', 'El Ksar');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Sud Ouest', 'Gafsa', 'Metlaoui', 'Metlaoui');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Sud Ouest', 'Gafsa', 'Oum El Araies', 'Metlaoui');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Sud Ouest', 'Gafsa', 'Redeyef', 'Metlaoui');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Centre Ouest 1', 'Gafsa', 'Sidi Aich', 'Bir Lahfay');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Sud Ouest', 'Gafsa', 'Sidi Aïch', 'Gafsa');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Sud Ouest', 'Gafsa', 'Sned', 'Sned');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Nord Ouest 1', 'Jendouba', 'Ain Draham', 'Fernana');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Nord Ouest 1', 'Jendouba', 'Balta - Bou Aouane', 'Boussalem');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Nord Ouest 1', 'Jendouba', 'Bou Salem', 'Boussalem');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Nord Ouest 1', 'Jendouba', 'Fernana', 'Fernana');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Nord Ouest 1', 'Jendouba', 'Ghardimaou', 'Ghardimaou');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Nord Ouest 1', 'Jendouba', 'Jendouba', 'Jendouba');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Nord Ouest 1', 'Jendouba', 'Jendouba Nord', 'Jendouba');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Nord Ouest 1', 'Jendouba', 'Nabeur', 'Jendouba');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Nord Ouest 1', 'Jendouba', 'Oued Meliz', 'Jendouba');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Nord Ouest 1', 'Jendouba', 'Tabarka', 'Tabarka');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Centre Ouest 2', 'Kairouan', 'Bouhajla', 'Bouhajla');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Centre Ouest 2', 'Kairouan', 'EL Ouslatia', 'Oueslatia');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Centre Ouest 2', 'Kairouan', 'Echebika', 'Al Aghalba');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Centre Ouest 2', 'Kairouan', 'Echrarda', 'Bouhajla');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Centre Ouest 2', 'Kairouan', 'El Alâa', 'Alaa');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Centre Ouest 2', 'Kairouan', 'Haffouz', 'Haffouz');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Centre Ouest 2', 'Kairouan', 'Hajeb el Ayoun', 'Hajeb Lâayoun');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Centre Ouest 2', 'Kairouan', 'Kairouan Nord', 'Al Aghalba');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Centre Ouest 2', 'Kairouan', 'Kairouan Sud', 'Kairouan');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Centre Ouest 2', 'Kairouan', 'Nasrallah', 'Al Aghalba');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Centre Ouest 2', 'Kairouan', 'Ouled Chamekh', 'Kairouan');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Centre Ouest 2', 'Kairouan', 'Sbikha', 'Sbikha');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Centre Ouest 3', 'Kasserine', 'Djedeliane', 'Sbiba');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Centre Ouest 3', 'Kasserine', 'El Ayoun', 'Thala');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Centre Ouest 3', 'Kasserine', 'Ezzouhour', 'Kasserine');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Centre Ouest 3', 'Kasserine', 'Feriana', 'Feriana');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Centre Ouest 3', 'Kasserine', 'Foussana', 'Foussana');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Centre Ouest 3', 'Kasserine', 'Hassi Ferid', 'Sbitla');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Centre Ouest 3', 'Kasserine', 'Hidra', 'Thala');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Centre Ouest 3', 'Kasserine', 'Kasserine Nord', 'Kasserine');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Centre Ouest 3', 'Kasserine', 'Kasserine Sud', 'Kasserine');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Centre Ouest 3', 'Kasserine', 'Majel Bel Abbès', 'Feriana');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Centre Ouest 3', 'Kasserine', 'Oum El Araies', 'Feriana');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Centre Ouest 3', 'Kasserine', 'Sbeitla', 'Sbitla');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Centre Ouest 3', 'Kasserine', 'Sbiba', 'Sbiba');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Centre Ouest 3', 'Kasserine', 'Thala', 'Thala');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Sud Ouest', 'Kebili', 'Douz Nord', 'Douz');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Sud Ouest', 'Kebili', 'Douz Sud', 'Douz');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Sud Ouest', 'Kebili', 'Faouar', 'Douz');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Sud Ouest', 'Kebili', 'Kebeli Nord', 'Kébili');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Sud Ouest', 'Kebili', 'Kebili Sud', 'Kébili');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Sud Ouest', 'Kebili', 'Souk El Ahed', 'Kébili');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Nord Ouest 2', 'Le Kef', 'Dahmani', 'El Kef Ouest');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Nord Ouest 2', 'Le Kef', 'Djerissa', 'Tajerouine');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Nord Ouest 2', 'Le Kef', 'El Ksour', 'El Kef Ouest');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Nord Ouest 2', 'Le Kef', 'Es-Sers', 'Sers');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Nord Ouest 2', 'Le Kef', 'Kalâat Khasbah', 'Tajerouine');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Nord Ouest 2', 'Le Kef', 'Kalâat Snan', 'Tajerouine');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Nord Ouest 2', 'Le Kef', 'Kef Est', 'El Kef');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Nord Ouest 2', 'Le Kef', 'Kef Ouest', 'El Kef');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Nord Ouest 2', 'Le Kef', 'Nebeur', 'El Kef');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Nord Ouest 2', 'Le Kef', 'Sakiet Sidi Youssef', 'Sakiet Sidi Youssef');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Nord Ouest 2', 'Le Kef', 'Tajerouine', 'Tajerouine');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Sahel', 'Mahdia', 'Bou Merdès', 'El Jem');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Sahel', 'Mahdia', 'Chebba', 'Chebba');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Sahel', 'Mahdia', 'Chorbane', 'El Jem');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Sahel', 'Mahdia', 'El Djem', 'El Jem');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Sahel', 'Mahdia', 'Essouassi', 'El Jem');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Centre Ouest 2', 'Mahdia', 'Hebira', 'Bouhajla');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Sahel', 'Mahdia', 'Ksour Essef', 'Mahdia');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Sahel', 'Mahdia', 'Mahdia', 'Mahdia');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Sahel', 'Mahdia', 'Melloulech', 'Chebba');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Centre Ouest 2', 'Mahdia', 'Ouled Chamekh', 'Kairouan');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Sahel', 'Mahdia', 'Sidi Alouane', 'El Jem');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'GT2', 'Manouba', 'Borj Amri', 'Mornaguia');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'GT2', 'Manouba', 'Djedeida', 'Tebourba');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'GT2', 'Manouba', 'Douar Hicher', 'Douar Hicher');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'GT2', 'Manouba', 'El Battane', 'Tebourba');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'GT2', 'Manouba', 'Mannouba', 'Douar Hicher');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'GT2', 'Manouba', 'Mornaguia', 'Mornaguia');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'GT2', 'Manouba', 'Oued Ellil', 'Oued Ellil');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'GT2', 'Manouba', 'Tebourba', 'Tebourba');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Sud Est', 'Medenine', 'Ben Guerdane', 'Benguerdenne');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Sud Est', 'Medenine', 'Beni Khedech', 'Medenine');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Sud Est', 'Medenine', 'Djerba Ajim', 'Jerba');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Sud Est', 'Medenine', 'Djerba Houmet Souk', 'Jerba');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Sud Est', 'Medenine', 'Djerba Midoun', 'Jerba');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Sud Est', 'Medenine', 'Medenine Nord', 'Medenine');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Sud Est', 'Medenine', 'Medenine Sud', 'Medenine');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Sud Est', 'Medenine', 'Sidi Makhloulf', 'Medenine');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Sud Est', 'Medenine', 'Zarzis', 'Zarzis');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Sahel', 'Monastir', 'Bekalta', 'Moknine');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Sahel', 'Monastir', 'Bembla', 'Jammel');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Sahel', 'Monastir', 'Beni Hassen', 'Jammel');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Sahel', 'Monastir', 'Jammel', 'Jammel');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Sahel', 'Monastir', 'Ksar Helal', 'Ksar Hellal');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Sahel', 'Monastir', 'Ksibet El Mediouni', 'Jammel');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Sahel', 'Monastir', 'Moknine', 'Moknine');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Sahel', 'Monastir', 'Monastir', 'Monastir');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Sahel', 'Monastir', 'Ouerdanine', 'Msaken');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Sahel', 'Monastir', 'Sahline', 'Monastir');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Sahel', 'Monastir', 'Sayada-Lamta Bou-Hjar', 'Ksar Hellal');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Sahel', 'Monastir', 'Teboulba', 'Moknine');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Sahel', 'Monastir', 'Zermadine', 'Jammel');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Cap Bon', 'Nabeul', 'Beni Khalled', 'Béni Khalled');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Cap Bon', 'Nabeul', 'Beni khiar', 'Nabeul');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Cap Bon', 'Nabeul', 'Bou Argoub', 'Grombalia');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Cap Bon', 'Nabeul', 'Dar Châabane El Fehri', 'Nabeul');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Cap Bon', 'Nabeul', 'El Haouaria', 'Kélibia');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Cap Bon', 'Nabeul', 'El Mida', 'Menzel Temim');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Cap Bon', 'Nabeul', 'Grombalia', 'Grombalia');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Cap Bon', 'Nabeul', 'Hammam El Guezaz', 'Kélibia');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Cap Bon', 'Nabeul', 'Hammamet', 'Hammamet');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Cap Bon', 'Nabeul', 'Kelibia', 'Kélibia');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Cap Bon', 'Nabeul', 'Korba', 'Korba');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Cap Bon', 'Nabeul', 'Menzel Bouzelfa', 'Menzel Bouzelfa');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Cap Bon', 'Nabeul', 'Menzel Temime', 'Menzel Temim');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Cap Bon', 'Nabeul', 'Nabeul', 'Nabeul');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Cap Bon', 'Nabeul', 'Soliman', 'Soliman');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Cap Bon', 'Nabeul', 'Takelsa', 'Menzel Bouzelfa');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Sahel', 'Sfax', 'Agareb', 'Sfax');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Sahel', 'Sfax', 'Amra', 'Jbeniana');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Sahel', 'Sfax', 'Bir ali Ben Kelifa', 'Sfax');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Sahel', 'Sfax', 'Djebeniana', 'Jbeniana');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Sahel', 'Sfax', 'El Hencha', 'El Jem');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Sahel', 'Sfax', 'Ghraiba', 'Sfax');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Sahel', 'Sfax', 'Kerkenah', 'Sakiet Eddayer');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Sahel', 'Sfax', 'Mahres', 'Sfax');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Sahel', 'Sfax', 'Menzel Chaker', 'Sfax');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Sahel', 'Sfax', 'Sakiet Eddaïer', 'Sakiet Eddayer');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Sahel', 'Sfax', 'Sakiet Ezzit', 'Sakiet Eddayer');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Sahel', 'Sfax', 'Sfax Ouest', 'Sfax');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Sahel', 'Sfax', 'Sfax Sud', 'Sfax');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Sahel', 'Sfax', 'Sfax Ville', 'Sakiet Eddayer');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Sud Est', 'Sfax', 'Skhira', 'Skhira');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Sahel', 'Sfax', 'Tina', 'Sfax');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Centre Ouest 1', 'Sidi Bouzid', 'Bir El Hafey', 'Bir Lahfay');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Centre Ouest 1', 'Sidi Bouzid', 'Cebalet Ouled Asker', 'Jelma');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Centre Ouest 1', 'Sidi Bouzid', 'Jilma', 'Jelma');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Centre Ouest 1', 'Sidi Bouzid', 'Meknassy', 'Souk Ejdid');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Sud Ouest', 'Sidi Bouzid', 'Menzel Bouzaïenne', 'Sned');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Sud Est', 'Sidi Bouzid', 'Mezzouna', 'Skhira');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Centre Ouest 1', 'Sidi Bouzid', 'Ouled Haffouz', 'Sidi-Bouzid');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Centre Ouest 1', 'Sidi Bouzid', 'Regueb', 'Regueb');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Centre Ouest 1', 'Sidi Bouzid', 'Sidi Ali Ben Aoûn', 'Bir Lahfay');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Centre Ouest 1', 'Sidi Bouzid', 'Sidi Bouzid Est', 'Sidi-Bouzid');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Centre Ouest 1', 'Sidi Bouzid', 'Sidi Bouzid Ouest', 'Sidi-Bouzid');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Centre Ouest 1', 'Sidi Bouzid', 'Souk Jedid', 'Souk Ejdid');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Nord Ouest 2', 'Siliana', 'Bargou', 'Bargou');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Nord Ouest 2', 'Siliana', 'Bou Arada', 'BOUARADA');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Nord Ouest 2', 'Siliana', 'Bourouis', 'El-Krib');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Nord Ouest 2', 'Siliana', 'El Aroussa', 'BOUARADA');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Nord Ouest 2', 'Siliana', 'El Krib', 'El-Krib');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Nord Ouest 2', 'Siliana', 'Er-Rouhia', 'Makthar');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Nord Ouest 2', 'Siliana', 'Gaâfour', 'Siliana');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Nord Ouest 2', 'Siliana', 'Kesra', 'Makthar');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Nord Ouest 2', 'Siliana', 'Makthar', 'Makthar');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Nord Ouest 2', 'Siliana', 'Siliana Nord', 'Siliana');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Nord Ouest 2', 'Siliana', 'Siliana Sud', 'Siliana');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Sahel', 'Sousse', 'Akouda', 'Akouda/Kalâa-Kbira');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Cap Bon', 'Sousse', 'Bouficha', 'Hammamet');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Sahel', 'Sousse', 'Enfidha', 'Enfidha');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Sahel', 'Sousse', 'Hammam Sousse', 'Akouda/Kalâa-Kbira');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Sahel', 'Sousse', 'Hergla', 'Akouda/Kalâa-Kbira');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Sahel', 'Sousse', 'Kalaa Sghira', 'Akouda/Kalâa-Kbira');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Sahel', 'Sousse', 'Kalaâ Kebira', 'Akouda/Kalâa-Kbira');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Sahel', 'Sousse', 'Kalaâ Seghira', 'Sousse');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Sahel', 'Sousse', 'Kondar', 'Akouda/Kalâa-Kbira');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Sahel', 'Sousse', 'M''saken', 'Msaken');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Sahel', 'Sousse', 'Sidi Bou Ali', 'Akouda/Kalâa-Kbira');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Centre Ouest 2', 'Sousse', 'Sidi El Heni', 'Kairouan');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Sahel', 'Sousse', 'Sidi El Héni', 'Msaken');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Sahel', 'Sousse', 'Sousse Jaouhara', 'Sousse');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Sahel', 'Sousse', 'Sousse Jawhara', 'Sousse');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Sahel', 'Sousse', 'Sousse Medina', 'Sousse');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Sahel', 'Sousse', 'Sousse Riadh', 'Sousse');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Sahel', 'Sousse', 'Sousse Sidi Abdelhamid', 'Sousse');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Sahel', 'Sousse', 'Zaouia - Ksiba - Thrayet', 'Sousse');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Sud Est', 'Tataouine', 'Bir Lahmar', 'Medenine');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Sud Est', 'Tataouine', 'Ghomrassen', 'Tataouine');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Sud Est', 'Tataouine', 'Smâr', 'Tataouine');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Sud Est', 'Tataouine', 'Tataouine Nord', 'Tataouine');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Sud Est', 'Tataouine', 'Tataouine Sud', 'Tataouine');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Sud Ouest', 'Tozeur', 'Degach', 'Tozeur');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Sud Ouest', 'Tozeur', 'Hazoua', 'Nafta');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Sud Ouest', 'Tozeur', 'Nefta', 'Nafta');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Sud Ouest', 'Tozeur', 'Tameghza', 'Tozeur');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Sud Ouest', 'Tozeur', 'Tozeur', 'Tozeur');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'GT1', 'Tunis', 'Bab El Bhar', 'Medina');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'GT1', 'Tunis', 'Bab Souika', 'Medina');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'GT1', 'Tunis', 'Carthage', 'El Kram');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'GT1', 'Tunis', 'Cité El Khadhra', 'Ariana-Borj Louzir');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'GT2', 'Tunis', 'Djebel Djelloud', 'Ben Arous');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'GT1', 'Tunis', 'El Hrairia', 'Sidi Hessine');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'GT2', 'Tunis', 'El Kabaria', 'Kabaria');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'GT1', 'Tunis', 'El Menzah', 'Omrane');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'GT1', 'Tunis', 'El Omrane', 'Omrane');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'GT1', 'Tunis', 'El Omrane Supérieur', 'Omrane');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'GT2', 'Tunis', 'El Ouardia', 'Ben Arous');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'GT1', 'Tunis', 'Ettahrir', 'Omrane');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'GT1', 'Tunis', 'Ezzouhour', 'Zouhour');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'GT1', 'Tunis', 'La Goulette', 'El Kram');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'GT1', 'Tunis', 'La Marsa', 'Marsa');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'GT1', 'Tunis', 'La Medina', 'Medina');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'GT1', 'Tunis', 'Le Bardo', 'Zouhour');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'GT1', 'Tunis', 'Le Kram', 'El Kram');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'GT1', 'Tunis', 'Sidi El Béchir', 'Medina');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'GT1', 'Tunis', 'Sidi Hassine', 'Sidi Hessine');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'GT1', 'Tunis', 'Sijoumi', 'Zouhour');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Cap Bon', 'Zaghouan', 'Bir Mchergua', 'Zaghouan');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Cap Bon', 'Zaghouan', 'El Fahs', 'El Fahs');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Cap Bon', 'Zaghouan', 'En-Nadhour', 'ENNADHOUR');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Cap Bon', 'Zaghouan', 'Ez-Zeriba', 'Zaghouan');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Cap Bon', 'Zaghouan', 'Saouaf', 'ENNADHOUR');
INSERT INTO agence (id, region, gouvernorat, delegation, agence) VALUES (UUID(), 'Cap Bon', 'Zaghouan', 'Zaghouan', 'Zaghouan');